application: rubuffbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /buff/
  script: main.app
  login: admin
- url: /
  static_files: index.html
  upload: index.html
- url: /faq/
  static_files: faq.html
  upload: faq.html
- url: /web/buff/
  script: web.app
  login: admin
- url: /web/
  static_files: web.html
  upload: web.html
- url: /flush/
  script: flush.app
  login: admin